# filebeat.inputs:
#   - type: log
#     paths:
#       - /var/lib/docker/containers/*/*.log
#     json.keys_under_root: true
#     json.add_error_key: true
#     processors:
#       - add_docker_metadata: ~

# output.elasticsearch:
#   hosts: ["http://elasticsearch:9200"]

# filebeat.inputs:
#   - type: log
#     enabled: true
#     paths:
#       - /var/log/*.log
#       - /path/to/your/log/files/*.log

# fields:
#   type: filebeat

# output.logstash:
#   hosts: ["logstash:5044"]

filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - add_host_metadata:

output.logstash:
  hosts: ["logstash:5044"]
