metricbeat.modules:
  - module: docker
    metricsets:
      - container
      - cpu
      - memory
      - network
      - diskio
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
