metricbeat.modules:
  - module: docker
    metricsets: ["cpu", "memory", "network", "container"]
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    processors:
      - add_docker_metadata: ~
      - drop_event.when.not.contains:
          container.name: "jenkins"

  - module: system
    metricsets: ["cpu", "memory", "network", "process"]
    period: 10s
    enabled: true
    processes:
      - "java" 
      - "docker"

  - module: elasticsearch
    metricsets: ["node_stats", "cluster_stats"]
    period: 10s
    enabled: true
    hosts: ["http://elasticsearch:9200"]

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

