# metricbeat.modules:
#   - module: docker
#     metricsets:
#       - container
#       - cpu
#       - memory
#       - network
#       - diskio
#     hosts: ["unix:///var/run/docker.sock"]
#     period: 10s

# fields:
#   type: metricbeat

# output.logstash:
#   hosts: ["logstash:5044"]
#   ssl.enabled: false


metricbeat.modules:

  - module: system
    metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
      - diskio
      - filesystem
      - uptime
    enabled: true
    period: 10s
    # hostfs: "/hostfs"
    # processors:
    # - drop_event:
    #     when:
    #       not:
    #         contains:
    #           docker.container.name: "pipeline-simulator"

  - module: docker
    metricsets: ["container", "cpu", "diskio", "event", "healthcheck", "info", "memory", "network"]
    hosts: ["unix:///var/run/docker.sock"]
    enabled: true
    period: 10s
    # processors:
    # - drop_event:
    #     when:
    #       not:
    #         contains:
    #           docker.container.name: "pipeline-simulator"

  - module: logstash
    metricsets: ["node", "node_stats"]
    enabled: true
    period: 10s
    hosts: ["logstash:9600"]

  - module: elasticsearch
    metricsets: ["node", "node_stats", "cluster_stats"]
    enabled: true
    period: 10s
    hosts: ["http://elasticsearch:9200"]

metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true

output.logstash:
  hosts: ["logstash:5044"]

setup.kibana:
  host: "http://kibana:5601"
