metricbeat.modules:
  - module: docker
    metricsets:
      - container
      - cpu
      - memory
      - network
      - diskio
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

# metricbeat.modules:
#   - module: system
#     metricsets:
#       - cpu
#       - memory
#       - network
#       - container
#       - diskio
#     enabled: true
#     period: 10s
#     hosts: ["192.168.64.2"]

fields:
  type: metricbeat

output.logstash:
  hosts: ["logstash:5044"]
